# https://clangd.llvm.org/config
CompileFlags:
  Add:  [-xc++, -Wall]
  Remove: -W*
  Compiler: clang++  
Index:
  Background: Skip
Style:
  FullyQualifiedNamespaces: NO
Diagnostics:
  UnusedIncludes: Strict
InlayHints:
  Designators: Yes
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
Hover:
  ShowAKA: Yes
